/**
 * Single source of the public policy texts (V2-RSO-PRODUCTION-READINESS-01). Rendered by the #/privacy, #/terms and
 * #/product pages and generated into docs/PRIVACY_POLICY.md and docs/TERMS_OF_SERVICE.md (`npm run docs:legal`), so
 * the website and the application package cannot drift. English first (application review), with a short Traditional
 * Chinese summary. Statements describe what is technically true TODAY and what is PLANNED for an approved RSO mode.
 */
export const PRODUCT_NAME = '哥布林大調查';
export const PRODUCT_NAME_EN = 'Goblin Survey (哥布林大調查)';
export const POLICY_VERSION = 'policy-draft-2026-10-09';
export const POLICY_DATE = '2026-10-09';
export const REPOSITORY_ISSUES_URL = 'https://github.com/scottpuppylu/valorant-squad-analytics-v2/issues';
/** Private contact for privacy, data-access, deletion and consent requests (publication explicitly approved by the operator, 2026-10-09). */
export const PRIVATE_CONTACT_EMAIL = 'casper880115@gmail.com';

/**
 * Riot Games Developer API Policy legal boilerplate (General Policies, "[Your product]" placeholder), retrieved
 * 2026-10-09 from developer.riotgames.com/policies/general. Must stay readily visible to players (site footer).
 */
export const RIOT_LEGAL_BOILERPLATE = `${PRODUCT_NAME} isn't endorsed by Riot Games and doesn't reflect the views or opinions of Riot Games or anyone officially involved in producing or managing Riot Games properties. Riot Games, and all associated properties are trademarks or registered trademarks of Riot Games, Inc.`;
export const NON_AFFILIATION_ZH = `${PRODUCT_NAME}是獨立的第三方社群工具，未經 Riot Games 認可，也不代表 Riot Games 的立場。`;

/** VALORANT opt-in disclaimer for account linking. DRAFT: Riot has not reviewed or approved this text. */
export const OPT_IN_DISCLAIMER = {
  label: 'DRAFT FOR RIOT REVIEW',
  en: [
    'Linking your Riot account is optional and only happens when you start it.',
    'Linking authorizes this service to access your VALORANT player data, but only within the permissions you turn on: data collection, group visibility and public derived analytics are separate switches, all OFF by default.',
    'If you allow group visibility, members of your invite-only group can see your player statistics. If you also allow public derived analytics, derived statistics (never raw identifiers, match ids or positions) can appear on the public group page — so linking with those permissions makes that player data public.',
    'Other people cannot see your player-specific information unless you have granted the matching permission. You can revoke any permission or unlink at any time; this stops future collection and publication eligibility and requests removal processing.',
  ],
  zh: [
    '連結 Riot 帳號是選擇性的，只有你自己按下才會開始。',
    '連結代表你授權本服務在你開啟的權限範圍內存取你的 VALORANT 玩家資料：「資料收集」、「群組可見」、「公開衍生分析」是三個獨立開關，預設全部關閉。',
    '開啟「群組可見」後，你所在的邀請制群組成員可以看到你的玩家統計；再開啟「公開衍生分析」後，衍生統計（不含原始帳號識別碼、對戰編號或位置）可能出現在公開的群組頁面，也就是你的資料會因此公開。',
    '除非你開啟對應權限，其他人看不到你的個人玩家資料。你可以隨時撤回任何權限或解除連結；這會停止未來的收集與公開資格，並送出資料移除處理請求。',
  ],
} as const;

export interface PolicySection { id: string; title: string; paragraphs: readonly string[]; items?: readonly string[] }
export interface PolicyDocument { title: string; summaryZh: readonly string[]; sections: readonly PolicySection[] }

export const PRIVACY_POLICY: PolicyDocument = {
  title: 'Privacy Policy',
  summaryZh: [
    '目前網站只使用合成示範資料：沒有帳號登入、沒有 Riot 帳號連結、不收集任何訪客的遊戲資料。',
    '未來若取得 Riot 正式核准（Production Key 與 RSO），才會在玩家主動連結並逐項同意後收集資料；預設全部拒絕，可隨時撤回。',
  ],
  sections: [
    { id: 'status', title: '1. Current status vs. future approved mode', paragraphs: [
      'CURRENT SYNTHETIC DEMO: this website shows fictional members and fictional matches generated by an offline fake data source. There is no sign-in, no Riot account linking, no form that collects personal data, and the website itself makes no request to Riot or any other game-data provider. The site is a static website hosted on GitHub Pages and loads only static files.',
      'FUTURE APPROVED RSO MODE (not live): if Riot Games approves a Production API key and a Riot Sign On (RSO) client for this product, players will be able to link a Riot account through RSO and grant permissions as described below. Nothing in that mode is live today.',
      'PRIVATE LOCAL EVALUATION DATA: during earlier development the operator collected match data for a small friend group through a third-party VALORANT API on the operator\'s own machine. That dataset is private, has never been published on this website, and is not used for any public page. Its members are treated as NOT having given product consent: they must re-consent explicitly before any of their data could be shown anywhere.',
    ] },
    { id: 'categories', title: '2. Data categories', paragraphs: ['The table distinguishes what exists today from what the approved mode would process.'], items: [
      'Website visitors (today): the site sets no cookies and runs no analytics. The hosting provider (GitHub) may process technical request data such as IP addresses under its own privacy statement.',
      'Product account data (future): a product user id and a display name.',
      'External identity references (future): a verified Riot account reference obtained through RSO, stored privately and never shown publicly.',
      'Consent metadata (future): the four permission states, policy version, and an append-only history of changes (who, when, previous and new state).',
      'Group and invite metadata (future): groups, memberships, roles, and invites (only a hash of each invite token is stored).',
      'Match / game data (future, only with Data Collection permission): VALORANT match history and match details of the linked account, obtained by a local worker from the official Riot API.',
      'Derived analytics (future): statistics computed from collected matches (for example per-member performance statistics, shared-match comparisons, historical team-fit). These are community statistics, not an official rank, MMR or Elo.',
      'Provider provenance (future): which source and software version produced a record, kept for accuracy and auditing; raw provider identifiers stay private.',
      'Audit and security metadata (future): security-relevant actions (for example consent changes, invite use, sync requests) recorded with ids and codes only — never tokens or account identifiers.',
    ] },
    { id: 'purpose', title: '3. Purpose', paragraphs: [
      'Data would be processed only to provide invite-only groups of players with their own and group-permitted performance statistics, historical derived analytics, shared-match comparisons between members, and historical team-composition suggestions. It is not used for opponent scouting, advertising profiles, selling data, or building a global player database.',
    ] },
    { id: 'consent', title: '4. Opt-in and permissions', paragraphs: [
      'Linking a Riot account is optional and user-initiated. Being invited to or joining a group never grants any data access.',
      'Permissions are separate and all OFF by default: Data Collection (may we fetch and store your match data), Group Visibility (may your group see your statistics), Public Derived Analytics (may derived statistics appear on a public group page). A verified account connection is a fact, not a permission. Player-specific statistics are never shown before you opt in.',
    ] },
    { id: 'publication', title: '5. Publication eligibility', paragraphs: [
      'Your derived statistics can appear in a public group snapshot only if your membership is active, the group is active, and you have granted Group Visibility and Public Derived Analytics (which also require Data Collection and a verified connection). Public pages never contain account identifiers, raw match ids, positions or view directions. Members who have not opted in do not appear in other members\' comparisons either.',
    ] },
    { id: 'retention', title: '6. Retention', paragraphs: ['No fixed legal retention periods are promised yet; classes and rules are:'], items: [
      'Control-plane metadata (groups, memberships, invites): OPERATIONAL_NECESSITY.',
      'Consent history and audit records: OPERATIONAL_NECESSITY (needed to prove what was permitted); exact period TBD_WITH_POLICY_REVIEW.',
      'Provider identity reference: UNTIL_USER_REVOCATION (cleared when you unlink).',
      'Collected match evidence: UNTIL_USER_REVOCATION of Data Collection, subject to the deletion rules below; exact period TBD_WITH_POLICY_REVIEW.',
      'Derived analytics: recomputed from current evidence; removed from future publications when eligibility ends.',
      'Public snapshots: immutable static files; a new snapshot without your data replaces the active one after revocation; older files TBD_WITH_POLICY_REVIEW.',
      'Revocation records: OPERATIONAL_NECESSITY.',
    ] },
    { id: 'revocation', title: '7. Revocation and deletion', paragraphs: ['These are different operations with different effects:'], items: [
      'Revoke Public Derived Analytics: you leave future public snapshots; collection may continue.',
      'Revoke Group Visibility: your group no longer sees your statistics; public eligibility also ends.',
      'Revoke Data Collection: future collection stops, public eligibility ends, and a data-revocation request is sent to the data store, which removes your player-attributable precise spatial evidence (positions and view directions). Shared, non-attributable match records involving other players are not instantly deleted.',
      'Disconnect your Riot account: the private account reference is cleared and every permission that depends on it is revoked as above.',
      'Leave a group (or be removed): you stop being eligible for that group\'s pages and syncs; it does not by itself delete data.',
      `Request deletion: email ${PRIVATE_CONTACT_EMAIL}; handling of other stored records on request is planned and its exact process is TBD_WITH_POLICY_REVIEW.`,
    ] },
    { id: 'third-parties', title: '8. Third-party services', paragraphs: [
      'Today: GitHub (website hosting). Future approved mode: Riot Games (Riot Sign On and the official VALORANT API) as the intended data source. A third-party VALORANT API was used only for private local evaluation and is not the planned public data backbone. Data is never sold.',
    ] },
    { id: 'security', title: '9. Security', paragraphs: [
      'No API key or credential is ever placed in the website or the public repository. Public pages are built from an allowlist that rejects private fields. In the planned mode: provider account references stay private, invite tokens are stored only as hashes, permissions default to deny, security actions are audit-logged, and data collection runs on a local worker that only makes outbound HTTPS requests. No system is perfectly secure; known gaps are listed in the application package.',
    ] },
    { id: 'contact', title: '10. Contact', paragraphs: [
      `General, non-sensitive questions: the project's public issue tracker (${REPOSITORY_ISSUES_URL}). Do not post personal data there.`,
      `Private requests — privacy questions, data access, data deletion and consent questions: email ${PRIVATE_CONTACT_EMAIL}.`,
    ] },
    { id: 'updates', title: '11. Changes to this policy', paragraphs: [
      `Version ${POLICY_VERSION} (${POLICY_DATE}). This is a draft prepared for the planned Riot application. Material changes will be shown on this page with a new version and date before they apply to collected data; permissions you granted under an older version are not silently extended.`,
    ] },
  ],
};

export const TERMS_OF_SERVICE: PolicyDocument = {
  title: 'Terms of Service',
  summaryZh: [
    '本服務是給私人、邀請制朋友群組使用的社群表現分析工具；目前只有合成示範資料。',
    '禁止偵查對手、作弊輔助，也不提供官方牌位、MMR 或 Elo 的替代品。',
  ],
  sections: [
    { id: 'purpose', title: '1. Service purpose', paragraphs: [
      'The service gives private, invite-only groups of VALORANT players transparent community statistics about their own matches: member performance statistics, shared-match comparisons, and historical team-composition suggestions. Today the website is a synthetic demonstration only.',
    ] },
    { id: 'eligibility', title: '2. Eligibility', paragraphs: [
      'In the planned approved mode you need a Riot account in good standing that you are allowed to use under Riot Games\' own terms, and you must be invited to a group.',
    ] },
    { id: 'acceptable-use', title: '3. Acceptable use', items: [
      'No opponent scouting: the service does not show, and you may not use it to look up, opponents\' statistics before or during a match. There is no arbitrary Riot-ID lookup and no global player search.',
      'No cheating assistance: the service provides no real-time in-match information or instructions; Team Builder is historical, pre-/post-match planning only.',
      'No ranking replacement: statistics are group-internal community statistics, not an official rank, MMR, Elo, hidden rating or ladder, and must not be presented as one.',
      'No attempts to access other members\' data without their permission, to bypass security, or to scrape the service.',
      'No harassment of group members based on their statistics.',
    ], paragraphs: [] },
    { id: 'responsibilities', title: '4. Your responsibilities', paragraphs: [
      'Keep invite links private to the people you intend to invite, keep your own account secure, and only link a Riot account that you own.',
    ] },
    { id: 'linking', title: '5. Account linking and consent', paragraphs: [
      'Account linking (future, via Riot Sign On) is optional and user-initiated. Linking alone shares nothing: data collection, group visibility and public derived analytics are separate permissions, OFF by default, and can be revoked at any time. See the Privacy Policy and the account linking disclaimer.',
    ] },
    { id: 'groups', title: '6. Group and invite rules', paragraphs: [
      'Groups are private or invite-only. Invites are one-time and expire. Group owners and admins can invite and remove members; removing a member never grants or extends any data permission, and joining a group never grants data access.',
    ] },
    { id: 'availability', title: '7. Service availability', paragraphs: [
      'The service is a community project provided as is, without guaranteed uptime. Features may change or be discontinued; data sources may be unavailable or rate-limited.',
    ] },
    { id: 'limitations', title: '8. Analytics limitations', paragraphs: [
      'Statistics are estimates from the match history a data source makes visible. That history is provider-visible only and never guaranteed to be a complete career (lifetime completeness is not claimed). Low-sample statistics are marked as insufficient. Team Fit is relative historical lineup fit, not a win probability.',
    ] },
    { id: 'termination', title: '9. Termination and revocation', paragraphs: [
      'You can leave a group, revoke permissions or unlink your account at any time (effects are described in the Privacy Policy). The operator may remove accounts or groups that violate these terms.',
    ] },
    { id: 'riot', title: '10. Riot Games', paragraphs: [
      RIOT_LEGAL_BOILERPLATE,
      'This product is not an official Riot Games product, and no approval by Riot Games is implied. Riot Games may change or revoke API access at any time.',
    ] },
    { id: 'changes', title: '11. Changes', paragraphs: [
      `Version ${POLICY_VERSION} (${POLICY_DATE}), draft. Contact: ${PRIVATE_CONTACT_EMAIL} (privacy and data requests); general questions: see the Privacy Policy.`,
    ] },
  ],
};

/** Markdown rendering for docs/*.md (generated, never hand-edited). */
export function policyMarkdown(doc: PolicyDocument): string {
  const out = [`<!-- GENERATED from apps/web/src/legal.ts by \`npm run docs:legal\` — do not edit by hand. -->`, '', `# ${doc.title} — ${PRODUCT_NAME_EN}`, '',
    `Status: DRAFT (${POLICY_VERSION}). Mirrors the website page; the website renders the same source.`, '', '## 摘要（繁體中文）', '', ...doc.summaryZh.map((p) => `- ${p}`), ''];
  for (const s of doc.sections) {
    out.push(`## ${s.title}`, '');
    for (const p of s.paragraphs) out.push(p, '');
    if (s.items?.length) { for (const i of s.items) out.push(`- ${i}`); out.push(''); }
  }
  return `${out.join('\n').trimEnd()}\n`;
}
